name: Release
# 触发方式
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write  # 关键！确保 `GITHUB_TOKEN` 有写入权限
  
jobs:
  release:
    # 由于需要创建release所以需要设置写入权限
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # 我这里只需要两个平台，完整的可以参考官方的workflow
        platform: ["windows-latest"]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Install frontend dependencies
        run: yarn --no-frozen-lockfile
        # 使用tauri actions
      - name: Build the app
        id: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # 使用之前配置的私钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "ToolBox v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: false
      - name: Change latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 运行自己的脚本
        run: node scripts/updateLatest.mjs

      - name: Install MinIO Client
        run: |
          curl -sSL https://dl.min.io/client/mc/release/windows-amd64/mc.exe -o mc.exe
          mv mc.exe C:\Windows\System32\

      - name: Configure MinIO Client
        run: |
          mc alias set myminio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
      - name: Upload to MinIO S3
        run: |
          mc cp --recursive .\src-tauri\target\release\bundle\nsis\ myminio/apps/tools/${{ github.ref_name }}/ && mc cp --recursive .\src-tauri\target\release\bundle\msi\ myminio/apps/tools/${{ github.ref_name }}/
      - name: Upload latest.json to MinIO S3
        run: |
          mc cp --recursive .\latest.json myminio/apps/tools/
          
    #   - name: Upload assets
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     # 运行自己的脚本
    #     run: node scripts/updater.mjs
